### ISSUE TITLE
Unable to create plane parabolic mirror

### ISSUE THREAD

**Issue by OpoOpo** [caiuspetronius/Optometrika#2]
Hi, I am trying to do school project where I need to have planar parabolic mirros.
Is there a way to do them?

**Comment by alexschultze** [comment]
Example 6 gives an example for a parabolic mirror.

**Comment by alexschultze** [comment]
% parabolic mirror
mirror2 = Lens( [ 100 0 0 ], 40, -120, -1, { 'air' 'mirror' } ); % pay attention to the glass order here!
